definitions:
  entities.Admin:
    properties:
      email:
        type: string
      id:
        type: integer
      id_pegawai:
        type: integer
      name:
        type: string
      password:
        type: string
    required:
    - email
    - id_pegawai
    - name
    - password
    type: object
  entities.CallbackInvoice:
    properties:
      amount:
        type: integer
      bank_code:
        type: string
      created:
        type: string
      currency:
        type: string
      description:
        type: string
      external_id:
        type: string
      id:
        type: string
      is_high:
        type: boolean
      merchant_name:
        type: string
      paid_amount:
        type: integer
      paid_at:
        type: string
      payer_email:
        type: string
      payment_channel:
        type: string
      payment_destination:
        type: string
      payment_method:
        type: string
      status:
        type: string
      updated:
        type: string
      user_id:
        type: string
    type: object
  entities.Invoice:
    properties:
      buyer_address:
        type: string
      buyer_email:
        type: string
      buyer_name:
        type: string
      buyer_phone:
        type: string
      description:
        type: string
      due_date:
        type: string
      id:
        type: integer
      id_csv_file:
        type: integer
      id_payment_status:
        type: integer
      issuer_address:
        type: string
      issuer_email:
        type: string
      issuer_name:
        type: string
      issuer_phone:
        type: string
      tax:
        type: integer
      total:
        type: integer
    type: object
  entities.InvoicePaymentStatus:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
  entities.LoginAdmin:
    properties:
      id_pegawai:
        type: integer
      password:
        type: string
    required:
    - id_pegawai
    - password
    type: object
  entities.LoginUser:
    properties:
      email:
        type: integer
      password:
        type: string
    required:
    - email
    - password
    type: object
  entities.RegisterAdmin:
    properties:
      email:
        type: string
      id_pegawai:
        type: integer
      name:
        type: string
      password:
        type: string
    required:
    - email
    - id_pegawai
    - name
    - password
    type: object
  entities.RegisterUser:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
    required:
    - email
    - name
    - password
    type: object
  entities.SendCustomer:
    properties:
      body:
        type: string
      subject:
        type: string
      to:
        type: string
    type: object
  entities.TransactionRecord:
    properties:
      created_at:
        type: string
      id_invoice:
        type: integer
      id_invoice_payment:
        type: string
      id_user_payment:
        type: string
      updated_at:
        type: string
    type: object
  entities.User:
    properties:
      email:
        type: string
      id:
        type: integer
      name:
        type: string
      password:
        type: string
    required:
    - email
    - name
    - password
    type: object
host: backend-capstone-alta-golang-staging.up.railway.app
info:
  contact: {}
  description: This is Automatic Generate Invoice API Documentation
  title: Automatic Generate Invoice System API Documentation
  version: "2.0"
paths:
  /admin/invoice:
    get:
      consumes:
      - application/json
      description: Admin Get All Invoice User
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.Invoice'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entities.Invoice'
      security:
      - JWT: []
      summary: Get All Invoice
      tags:
      - Invoice
  /admin/invoice-payment-status:
    get:
      consumes:
      - application/json
      description: Admin can get all invoice payment status information
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.InvoicePaymentStatus'
      security:
      - JWT: []
      summary: Get All Invoice Payment Status Information
      tags:
      - Invoice Payment Status
    post:
      consumes:
      - application/json
      description: Admin can create invoice payment for table invoice
      parameters:
      - description: required
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/entities.InvoicePaymentStatus'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/entities.InvoicePaymentStatus'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entities.InvoicePaymentStatus'
      security:
      - JWT: []
      summary: Create Invoice Payment Status
      tags:
      - Invoice Payment Status
  /admin/invoice-payment-status/{id}:
    delete:
      consumes:
      - application/json
      description: Admin can delete invoice payment status information
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.InvoicePaymentStatus'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entities.InvoicePaymentStatus'
      security:
      - JWT: []
      summary: Delete Invoice Payment Status Information
      tags:
      - Invoice Payment Status
    get:
      consumes:
      - application/json
      description: Admin can get invoice payment status information by id
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.InvoicePaymentStatus'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/entities.InvoicePaymentStatus'
      security:
      - JWT: []
      summary: Get Invoice Payment Status Information by Id
      tags:
      - Invoice Payment Status
    put:
      consumes:
      - application/json
      description: User can update invoice payment status information
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      - description: required
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/entities.InvoicePaymentStatus'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.InvoicePaymentStatus'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entities.InvoicePaymentStatus'
      security:
      - JWT: []
      summary: Update Invoice Payment Status Information
      tags:
      - Invoice Payment Status
  /admin/invoice/{id}:
    get:
      consumes:
      - application/json
      description: Admin can Get Invoice User By ID
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.Invoice'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entities.Invoice'
      security:
      - JWT: []
      summary: Get Invoice User By ID
      tags:
      - Invoice
  /admin/login:
    post:
      consumes:
      - application/json
      description: Login User Admin
      parameters:
      - description: required
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/entities.LoginAdmin'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.Admin'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entities.Admin'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/entities.Admin'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entities.Admin'
      summary: Login User Admin
      tags:
      - Auth
  /admin/payment/xendit/invoice:
    get:
      consumes:
      - application/json
      description: Admin can get all xendit payment invoice
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.TransactionRecord'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/entities.TransactionRecord'
      security:
      - JWT: []
      summary: Get All Xendit Payment Invoice
      tags:
      - InvoiceTransaction
  /admin/payment/xendit/invoice/{id}:
    get:
      consumes:
      - application/json
      description: Admin can get xendit payment invoice by id
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.TransactionRecord'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/entities.TransactionRecord'
      security:
      - JWT: []
      summary: Get Xendit Payment Invoice By ID
      tags:
      - InvoiceTransaction
    post:
      consumes:
      - application/json
      description: Admin can create payment invoice using xendit
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/entities.TransactionRecord'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entities.TransactionRecord'
      security:
      - JWT: []
      summary: Create Payment Invoice Using Xendit
      tags:
      - InvoiceTransaction
  /admin/payment/xendit/invoice/callback:
    post:
      consumes:
      - application/json
      description: Xendit can callback by this route if customer is have been paying
        or the invoice is expired
      parameters:
      - description: required
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/entities.CallbackInvoice'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.CallbackInvoice'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/entities.CallbackInvoice'
      security:
      - JWT: []
      summary: Xendit can callback by using this route
      tags:
      - CallbackInvoice
  /admin/payment/xendit/invoice/expire/{id}:
    get:
      consumes:
      - application/json
      description: Admin can expired xendit payment invoice
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.TransactionRecord'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/entities.TransactionRecord'
      security:
      - JWT: []
      summary: Expired Xendit Payment Invoice
      tags:
      - InvoiceTransaction
  /admin/register:
    post:
      consumes:
      - application/json
      description: Create User Admin
      parameters:
      - description: required
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/entities.RegisterAdmin'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/entities.Admin'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/entities.Admin'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entities.Admin'
      summary: Register User Admin
      tags:
      - Auth
  /admin/send/email:
    post:
      consumes:
      - application/json
      description: Admin can send email to customer for their invoice
      parameters:
      - description: required
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/entities.SendCustomer'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/entities.SendCustomer'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entities.SendCustomer'
      security:
      - JWT: []
      summary: Send Email to Customer
      tags:
      - Send Customer
  /admin/upload_csv:
    post:
      consumes:
      - multipart/form-data
      description: UploadCsvController with upload file csv
      parameters:
      - description: csv_file
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/entities.Invoice'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entities.Invoice'
      security:
      - JWT: []
      summary: Admin can Upload Csv
      tags:
      - Invoice
  /admin/user/{id_pegawai}:
    get:
      consumes:
      - application/json
      description: Admin can get by ID
      parameters:
      - description: id_pegawai
        in: path
        name: id_pegawai
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.Admin'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/entities.Admin'
      security:
      - JWT: []
      summary: Get User With name
      tags:
      - Auth
    put:
      consumes:
      - application/json
      description: Update User Admin
      parameters:
      - description: id_pegawai
        in: path
        name: id_pegawai
        required: true
        type: integer
      - description: required
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/entities.Admin'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.Admin'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entities.Admin'
      security:
      - JWT: []
      summary: Update User Admin
      tags:
      - Auth
  /user/login:
    post:
      consumes:
      - application/json
      description: Login User
      parameters:
      - description: required
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/entities.LoginUser'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entities.User'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/entities.User'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entities.User'
      summary: Login User
      tags:
      - Auth User
  /user/register:
    post:
      consumes:
      - application/json
      description: Create User Admin
      parameters:
      - description: required
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/entities.RegisterUser'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/entities.User'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/entities.User'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entities.User'
      summary: Register User
      tags:
      - Auth User
schemes:
- https
- http
securityDefinitions:
  JWT:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
